# Use the official Ubuntu image as the base
FROM bioconductor/bioconductor_docker:RELEASE_3_21-r-4.5.2

# Avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Copy the `.devcontainer/renv` folder to the container
COPY .devcontainer/renv /usr/local/share/renv-cache/renv

# Set appropriate permissions
RUN chmod -R 755 /usr/local/share/renv-cache/renv
